### ISSUE TITLE
case_statement do not include first comment line in scope_statement_list:

### ISSUE THREAD

**Issue by FabArd** [CyberShadow/tree-sitter-d#10]
Hi,

In the code below, the comment is not included in the  "scope_statement_list:" of  "case_statement:" which makes indentation incorrect for this line.

```
override bool handleAction(const Action a) {
    switch (a.id) {
        case IDEActions.EditPreferences:
            //showPreferences();
            return true;
        default:
            return super.handleAction(a);
    }
    return false;
}
```
```
                    case_statement:
                      argument_list:
                        postfix_expression:
                          primary_expression:
                            identifier:
                          identifier:
                      line_comment:
                      scope_statement_list:
                        statement_list_no_case_no_default:
                          return_statement:
                            expression:
                              primary_expression:

```
All lines after a "case" should be included in the scope of this "case" even if it is a comment.

**Comment by CyberShadow** [comment]
Hmm, both interpretations are correct... What about:

```d
case 1: // comment
case 2:
```

Here, there is no `StatementList`, only a `LineComment`.

What do you think?

How do other grammars solve this problem?

**Comment by WebFreak001** [comment]
in libdparse
```d
case 1: // comment
case 2:
	foo();
	break;
case 3:
	bar();
	goto default;
default:
	baz();
```

would be
```
CaseStatement 1 []
CaseStatement 2 [foo(), BreakStatement]
CaseStatement 3 [bar(), GotoStatement]
DefaultStatement [baz()]
```

+ a bunch of fluff around each ast node. Basically libdparse differentiates between parseStatements and parseStatementsNoCaseNoDefault. The latter is used inside cases and defaults to stop at case/default statements.

**Comment by CyberShadow** [comment]
Well, that's not the problem - the question is what to do with the comment node.

Could this be handled by an indentation rule instead of changing the tree-sitter grammar?

**Comment by WebFreak001** [comment]
we changed to what Roslyn does, they describe it in a bunch of detail. Basically the lexer first lexes all the tokens, then all comment and whitespace tokens, called "trivia", are moved into adjacent "source tokens". AST nodes then contain a slice of their source tokens, which in turn reference the trivia tokens, so you can reconstruct source code exactly as it was input, mostly without caring for whitespace or comments when moving stuff around.

I don't think it's a good idea to include comments inside the AST as dedicated nodes because they can basically appear anywhere and would make AST processing a whole lot more painful.

**Comment by CyberShadow** [comment]
Thank you for the insight. This repository hosts (and this issue discusses) an implementation of a D grammar for tree-sitter. As such, we need to have comments as separate nodes in order to be able to syntax-highlight (or, here, indent) them. I may have misunderstood and I apologize if I did, but your suggestion is inapplicable to the issue at hand.

The D grammar (and therefore this tree-sitter grammar, which is generated from the D grammar) does allow comments to appear anywhere. In the D grammar this is done by describing this informally, but in tree-sitter a special feature is used ("extras"). The feature still does cause comments to appear as nodes in the tree for the reasons above.

**Comment by FabArd** [comment]
To define the context of the problem, we have two entities:

- the d language and its syntax which is used by its compiler
- tree-sitter

The objectives of each are different:

- the syntax of the D language is to allow its compiler to generate machine code
- tree-sitter allows the programmer to write programs to be compiled by the compiler

Both objectives are as essential as each other.

Indeed a comment is totally useless for a compiler: it will not generate any code.
On the other hand, for tree-sitter a comment is very important because it must be highlighted by the
coloring and indented so that the programmer can take it into account.

It seems to me that the problem is not the comment but where it should be placed in the AST :

As WebFreak001 mentioned each "case" should have a block even if it is empty:

```
CaseStatement 1 []
CaseStatement 2 [foo(), BreakStatement]
CaseStatement 3 [bar(), GotoStatement]
DefaultStatement [baz()]

```
So in my opinion (correct me if I'm wrong), the solution to this problem would be to systematically have a
"scope_statement_list:" node after each "case".

For the following code :

```
switch (X) {
    case test1: // Comment1
    case test2:
        // Comment2
    case test3:
        // Comment3;
        return true;
    default:
        return false;
}
```
We should have :

```
switch_statement:
  expression:
    primary_expression:
      identifier:
  block_statement:
    statement_list:
      case_statement:  --> case test1:
        argument_list:
          primary_expression:
            identifier:
        scope_statement_list:
          line_comment:  -- > //comment 1
      case_statement:  --> case test2:
        argument_list:
          primary_expression:
            identifier:
        scope_statement_list:
          line_comment:  -- > //comment 2
      case_statement:  --> case test3:
        argument_list:
          primary_expression:
            identifier:
        scope_statement_list:
          line_comment: -- > //comment 3
            return_statement:
              expression:
                primary_expression:
      default_statement:  --> default case
        scope_statement_list:
          return_statement:
            expression:
              primary_expression:
```
We have a similar problem with the 'if' without block.
But I'll open a new issue to not complicate this one.
