### ISSUE TITLE
Impossible to indent a 'then_statement' without block

### ISSUE THREAD

**Issue by FabArd** [CyberShadow/tree-sitter-d#11]
Hi

It is impossible to indent the line below the second if in the following example:

```
override bool onMouseEvent(MouseEvent event) {
    bool result = super.onMouseEvent(event);
    if (event.doubleClick) {
        if (onItemDoubleClick !is null)
            onItemDoubleClick(this, selectedItemIndex);
    }
    return result;
}
```

Indeed this 'then_statement' has no child in the tree to distinguish it as a node to indent:

```
if_statement:
  expression:
    identity_expression:
      primary_expression:
        identifier:
      primary_expression:
  then_statement:
    expression_statement:
      expression:
```
I analyzed your grammar and I noticed that you did not allow the generation of the 'NonEmptyStatementNoCaseNoDefault' node.
It is this node that allows you to distinguish an if without a block:

```
IfStatement:
    if ( IfCondition ) ThenStatement
    if ( IfCondition ) ThenStatement else ElseStatement

ThenStatement:
    ScopeStatement

ScopeStatement:
    NonEmptyStatement
    BlockStatement

NonEmptyStatement:
    NonEmptyStatementNoCaseNoDefault
    CaseStatement
    CaseRangeStatement
    DefaultStatement
```
